//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 03:25:44 PM COT 
//

package coop.equidad.autos.automas.recibesolicitud;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Table1">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Operacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IdSolicitud" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Respuesta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IdSolicitudExistente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "table1" })
@XmlRootElement(name = "NewDataSet")
public class NewDataSet {

	@XmlElement(name = "Table1")
	public List<NewDataSet.Table1> table1;

	/**
	 * Gets the value of the table1 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the table1 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTable1().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link NewDataSet.Table1 }
	 * 
	 * 
	 */
	public List<NewDataSet.Table1> getTable1() {
		if (table1 == null) {
			table1 = new ArrayList<NewDataSet.Table1>();
		}
		return this.table1;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Operacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="IdSolicitud" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="Respuesta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *          &lt;element name="IdSolicitudExistente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "operacion", "idSolicitud", "respuesta", "idSolicitudExistente" })
	public static class Table1 {

		@XmlElement(name = "Operacion")
		protected String operacion;
		@XmlElement(name = "IdSolicitud")
		protected String idSolicitud;
		@XmlElement(name = "Respuesta")
		protected String respuesta;
		@XmlElement(name = "IdSolicitudExistente")
		protected String idSolicitudExistente;

		/**
		 * Gets the value of the operacion property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getOperacion() {
			return operacion;
		}

		/**
		 * Sets the value of the operacion property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setOperacion(String value) {
			this.operacion = value;
		}

		/**
		 * Gets the value of the idSolicitud property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getIdSolicitud() {
			return idSolicitud;
		}

		/**
		 * Sets the value of the idSolicitud property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setIdSolicitud(String value) {
			this.idSolicitud = value;
		}

		/**
		 * Gets the value of the respuesta property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRespuesta() {
			return respuesta;
		}

		/**
		 * Sets the value of the respuesta property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setRespuesta(String value) {
			this.respuesta = value;
		}

		public String getIdSolicitudExistente() {
			return idSolicitudExistente;
		}

		public void setIdSolicitudExistente(String idSolicitudExistente) {
			this.idSolicitudExistente = idSolicitudExistente;
		}

	}

}
